format_version: 3
pipelines:
  test:
    group: My-Pipelines
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git:
        git: https://github.com/makahou/gocd-test
        username: makahou
        shallow_clone: false
        auto_update: true
        branch: master
        encrypted_password: AES:XgtFfM5uM2XVgdWgI2QjDg==:epi/0qgwMyMHQggeaPnnhg==
    stages:
    - build1:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          run-build-task:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - Hello
                command: echo
                run_if: passed
